/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatAvatar: typeof import('./src/components/ChatAvatar.vue')['default']
    ChatEmptyState: typeof import('./src/components/ChatEmptyState.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./src/components/ChatMessageList.vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiArrowUp: typeof import('~icons/mdi/arrow-up')['default']
    IconMdiBrain: typeof import('~icons/mdi/brain')['default']
    IconMdiChatOutline: typeof import('~icons/mdi/chat-outline')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiKeyboard: typeof import('~icons/mdi/keyboard')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiMicrophone: typeof import('~icons/mdi/microphone')['default']
    IconMdiPaperclip: typeof import('~icons/mdi/paperclip')['default']
    IconMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IconMdiRobot: typeof import('~icons/mdi/robot')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
  }
}
